name: Test-Go

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-go:
    strategy:
      matrix:
        # Test minimum version (1.16), stable (1.20), and current (1.22)
        go-version: [1.16.x, 1.20.x, 1.22.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./test
    steps:

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v4

    - run: |
        echo "replace github.com/keeper-security/secrets-manager-go/core => ../core" >> go.mod

    - run: pwd; ls -la; cat go.mod

    - name: Run integration tests
      run: go test -p 1 ./...

    - name: Run core unit tests
      working-directory: ./core
      run: go test ./...
